### PR TITLE
Make Website CMS be wrapped in DefaultTemplate

### PR DESCRIPTION
**Pull request by warpech**
Implements #29 

This required to split the app in two: `Website` and `WebsiteProvider`

As a side feature, WebsiteProvider allows to nest templates in other surfaces, which is demonstrated by adding a Help panel on Website CMS Templates page.

To test, make sure you run `http://localhost:8080/website/resetdata` to load additional maps (SidebarTemplate) that have been created.

@diliger please review.

Screenshot:

2017-02-13 11_54_58-website - microsoft visual studio

### CODE REVIEW

**Comment by diliger** [comment]
Well, i read it and run it, it works.

But i want to get better into the logic.
Now there are two apps, Website and WebsiteProvider
From description: 

> Website app gives "Website CMS"
> WebsiteProvider app gives section wrapping

What happens inside, what handlers affected
for example if I request the URI `http://127.0.0.1:8080/website/cms/templates`

I see a handler in Website app 
`Handle.GET("/website/cms/templates", () => {`
And how the WebsiteProvider affects the output result?

**Comment by diliger** [comment]
Why the default `/Website` URI handles **WebsiteProvider** not the **Website** app?

**Comment by warpech** [comment]
Technically, the apps needed to be split, because I wanted to wrap Website CMS in a template. This was not possible in the same app, because it would require merging two responses from the same app as one level in JSON (currently we support only one response at a single level).

Conceptually, splitting into two apps has more benefits than that:

- Website CMS app is used for configuration of templates/surfaces and can be stopped when you are done with configuring
- WebsiteProvider is lightweight and used for providing surfaces.

If the above explanation is enough, I will add it to README.md. Glad that you've asked.

> Why the default `/Website URI` handles **WebsiteProvider** not the **Website** app?

That's clearly a mistake, thanks for reporting! I will fix.

**Comment by warpech** [comment]
> I see a handler in Website app 
`Handle.GET("/website/cms/templates", () => {`
And how the WebsiteProvider affects the output result?

This handler provides a partial for configuring templates/surfaces. WebsiteProvider wraps the response from this handler (or any other handler in any other app) and puts that response in a section/blending point of a template/surface.

**Comment by warpech** [comment]
I have added the above explanation in README and renamed handlers in WebsiteProvider to /WebsiteProvider/

**Comment by diliger** [comment]
Well, seems i got it, where the magic does.

> `Application.Current.Use((Request request, Response response) => {`

this executes for every request, looks for the template based on the URI in the database and wrap the response into template. 

Just for me the name WebsiteProvider is not very clear..
Maybe WebsiteTemplates or TemplatesProvider.

And why **Default** template means **Final**?

> `master.IsFinal = template.Default;`

**Comment by diliger** [comment]
Fixed code style for better look in ContentHandlers

**Comment by warpech** [comment]
Yes, it is exactly as you described.

> Just for me the name WebsiteProvider is not very clear..
Maybe WebsiteTemplates or TemplatesProvider.

"Website" and "WebsiteProvider" is not very bad, either. I think that "Template" and "TemplateProvider" would be even less clear.

The issue #15 renames the term "Templates" to "Surfaces".  So maybe SurfaceDesigner and SurfaceProvider would be better?

**Comment by diliger** [comment]
Okay, let it be "Website" and "WebsiteProvider".

**Comment by warpech** [comment]
> And why **Default** template means **Final**?
> `master.IsFinal = template.Default;`

WebsiteProvider works recursively, allowing you to wrap a surface in another surface.

Because of that, it would go into an infinite look of wrapping default template in the default template. The `IsFinal` property prevents that.

**Comment by warpech** [comment]
Thanks for the review, merging.

**Pull request merged**
