### PR TITLE
Compatibility fix for Starcounter 2.2 and 2.3

### PR DESCRIPTION
**Pull request by warpech**
This app was done for Starcounter 2.1 and had multiple problems in the current version. The following Pull Request attempts to fix all the problems that I have encountered.

Changes are explained in more details in the commit messages.

To test this, you need Website (`compatibility-fix`), Content (`compatibility-fix`), SignIn (`develop`), UserProfile (`master`)

@miyconst could you pls review?

### CODE REVIEW

**Comment by miyconst** [comment]
Looks good to me. Don't have time to check whether it works, but I believe it does.

**Comment by warpech** [comment]
I have commited few more fixes. I have big aspirations for this app, because within a month #12 should happen. 

Before this PR is submitted for a final review, I will do the following things:

- [ ] Explain in README.md the features of the Website CMS
  - Including how to use the "default template" mode
- [ ] Submit a sample "default template"
- [ ] Move the sample configuration to a separate app

**Comment by warpech** [comment]
I think this PR is ready for a final review.

If anyone needs starting instructions, they are in `README.md` in this branch.

cc @miyconst, @diliger

**Comment by warpech** [comment]
@diliger can you please do a final review and do the sample apps routine explained in the https://github.com/StarcounterPrefabs/Website/blob/compatibility-fix/README.md file.

Then we can merge this PR and do any following work as new branches from `develop`.

**Comment by warpech** [comment]
Great, merging to `develop`. Thanks @miyconst and @diliger!

**Pull request merged**
